name: Latest Blog Posts
on:
  schedule:
    # 10:00 UTC = 12:00 PM Egypt Time
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Pull in dev.to & Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 5
          feed_list: "https://dev.to/feed/freerave,https://medium.com/feed/@freerave"
          template: "$newline- [$title]($url) $newline"
          readme_path: "README.md"
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "üìù Update blog posts"
          file_pattern: "README.md"
